// 어휘팩. '핵심/권장'은 이 게임 내부의 선정 기준이며 공식 지정 목록이 아니다.
// 공식 어휘 등급(국립국어원 기초 어휘 목록, 한국어기초사전 등급)은 officialGrade에 따로 두고,
// 아직 대조하지 못했으므로 모두 null + sourceStatus '임시 선정'이다.
// 음절·자모 분해는 직접 적지 않고 hangul.ts가 계산한다 (tests/vocab.test.ts가 분해→재조합을 검사).

export type PackId = '4-6' | '7-8';
export type Tier = 'core' | 'recommended';
export type Domain = '가족' | '신체' | '음식' | '동물' | '생활용품' | '장소' | '자연' | '행동' | '상태' | '탈것' | '사람';

export interface VocabEntry {
  id: string;
  word: string;
  pack: PackId;
  tier: Tier;
  domain: Domain;
  /** 음원 목록(audio manifest)의 단어 음성 ID */
  wordAudioId: string;
  /** 단어 그림 ID (content/pictures.ts). 그림이 없는 단어는 그림 칸을 비운다. */
  pictureId: string;
  /** 게임 내부 선정 근거와 확인 상태 */
  source: string;
  sourceStatus: '임시 선정' | '대조 완료';
  /** 공식 자료 등급 (확인 전이면 null). 아동 연령 등급으로 바꿔 쓰지 않는다. */
  officialGrade: string | null;
  /** 소리와 표기가 거의 같은가 (학교→[학꾜] 같은 단어는 초기 독립 조합에서 피한다) */
  soundMatchesSpelling: boolean;
}

const PENDING = '게임 내부 임시 선정 (공식 목록 대조 전)';

function v(word: string, pack: PackId, tier: Tier, domain: Domain, soundMatchesSpelling = true): VocabEntry {
  return {
    id: word,
    word,
    pack,
    tier,
    domain,
    wordAudioId: `w_${word}`,
    pictureId: `p_${word}`,
    source: PENDING,
    sourceStatus: '임시 선정',
    officialGrade: null,
    soundMatchesSpelling,
  };
}

export const VOCAB: VocabEntry[] = [
  // 4~6세 팩 — 처음 20개
  v('수박', '4-6', 'core', '음식'),
  v('나무', '4-6', 'core', '자연'),
  v('바다', '4-6', 'core', '자연'),
  v('모자', '4-6', 'core', '생활용품'),
  v('오이', '4-6', 'core', '음식'),
  v('우유', '4-6', 'core', '음식'),
  v('가방', '4-6', 'core', '생활용품'),
  v('아기', '4-6', 'core', '가족'),
  v('엄마', '4-6', 'core', '가족'),
  v('아빠', '4-6', 'core', '가족'),
  v('다리', '4-6', 'core', '신체'),
  v('집', '4-6', 'core', '장소'),
  v('바나나', '4-6', 'recommended', '음식'),
  v('머리', '4-6', 'recommended', '신체'),
  v('사자', '4-6', 'recommended', '동물'),
  v('꼬리', '4-6', 'recommended', '신체'),
  v('나비', '4-6', 'recommended', '동물'),
  v('개미', '4-6', 'recommended', '동물'),
  v('자다', '4-6', 'recommended', '행동'),
  v('크다', '4-6', 'recommended', '상태'),
  // 4~6세 팩 — 추가분(2026-09-28). 마지막 인자 false는 소리와 표기가 다른 단어 (공룡→[공뇽], 로봇→[로볻])
  v('누나', '4-6', 'core', '가족'),
  v('오빠', '4-6', 'core', '가족'),
  v('코', '4-6', 'core', '신체'),
  v('눈', '4-6', 'core', '신체'),
  v('입', '4-6', 'core', '신체'),
  v('손', '4-6', 'core', '신체'),
  v('발', '4-6', 'core', '신체'),
  v('포도', '4-6', 'core', '음식'),
  v('두부', '4-6', 'core', '음식'),
  v('고기', '4-6', 'core', '음식'),
  v('밥', '4-6', 'core', '음식'),
  v('피자', '4-6', 'core', '음식'),
  v('고양이', '4-6', 'core', '동물'),
  v('곰', '4-6', 'core', '동물'),
  v('공룡', '4-6', 'core', '동물', false),
  v('오리', '4-6', 'core', '동물'),
  v('여우', '4-6', 'core', '동물'),
  v('하마', '4-6', 'core', '동물'),
  v('공', '4-6', 'core', '생활용품'),
  v('책', '4-6', 'core', '생활용품'),
  v('신발', '4-6', 'core', '생활용품'),
  v('우산', '4-6', 'core', '생활용품'),
  v('방', '4-6', 'core', '장소'),
  v('해', '4-6', 'core', '자연'),
  v('별', '4-6', 'core', '자연'),
  v('물', '4-6', 'core', '자연'),
  v('가다', '4-6', 'core', '행동'),
  v('보다', '4-6', 'core', '행동'),
  v('아프다', '4-6', 'core', '상태'),
  v('언니', '4-6', 'recommended', '가족'),
  v('이모', '4-6', 'recommended', '가족'),
  v('이마', '4-6', 'recommended', '신체'),
  v('허리', '4-6', 'recommended', '신체'),
  v('빵', '4-6', 'recommended', '음식'),
  v('토마토', '4-6', 'recommended', '음식'),
  v('고구마', '4-6', 'recommended', '음식'),
  v('치즈', '4-6', 'recommended', '음식'),
  v('기린', '4-6', 'recommended', '동물'),
  v('코끼리', '4-6', 'recommended', '동물'),
  v('개구리', '4-6', 'recommended', '동물'),
  v('고래', '4-6', 'recommended', '동물'),
  v('비누', '4-6', 'recommended', '생활용품'),
  v('바지', '4-6', 'recommended', '생활용품'),
  v('양말', '4-6', 'recommended', '생활용품'),
  v('베개', '4-6', 'recommended', '생활용품'),
  v('로봇', '4-6', 'recommended', '생활용품', false),
  v('길', '4-6', 'recommended', '장소'),
  v('가게', '4-6', 'recommended', '장소'),
  v('달', '4-6', 'recommended', '자연'),
  v('비', '4-6', 'recommended', '자연'),
  v('무지개', '4-6', 'recommended', '자연'),
  v('오다', '4-6', 'recommended', '행동'),
  v('놀다', '4-6', 'recommended', '행동'),
  v('느리다', '4-6', 'recommended', '상태'),
  v('빠르다', '4-6', 'recommended', '상태'),
  // 7~8세 팩 — 처음 20개
  v('연필', '7-8', 'core', '생활용품'),
  v('공책', '7-8', 'core', '생활용품'),
  v('가족', '7-8', 'core', '가족'),
  v('친구', '7-8', 'core', '가족'),
  v('동생', '7-8', 'core', '가족'),
  v('어깨', '7-8', 'core', '신체'),
  v('감자', '7-8', 'core', '음식'),
  v('당근', '7-8', 'core', '음식'),
  v('토끼', '7-8', 'core', '동물'),
  v('하늘', '7-8', 'core', '자연'),
  v('시장', '7-8', 'core', '장소'),
  v('달리다', '7-8', 'core', '행동'),
  v('할머니', '7-8', 'recommended', '가족'),
  v('사탕', '7-8', 'recommended', '음식'),
  v('거북', '7-8', 'recommended', '동물'),
  v('호랑이', '7-8', 'recommended', '동물'),
  v('구름', '7-8', 'recommended', '자연'),
  v('바람', '7-8', 'recommended', '자연'),
  v('그리다', '7-8', 'recommended', '행동'),
  v('기쁘다', '7-8', 'recommended', '상태'),
  // 7~8세 팩 — 추가분(2026-09-28)
  v('삼촌', '7-8', 'core', '가족'),
  v('아저씨', '7-8', 'core', '가족'),
  v('얼굴', '7-8', 'core', '신체'),
  v('가슴', '7-8', 'core', '신체'),
  v('팔', '7-8', 'core', '신체'),
  v('김치', '7-8', 'core', '음식'),
  v('딸기', '7-8', 'core', '음식'),
  v('호박', '7-8', 'core', '음식'),
  v('만두', '7-8', 'core', '음식'),
  v('계란', '7-8', 'core', '음식', false),
  v('강아지', '7-8', 'core', '동물'),
  v('병아리', '7-8', 'core', '동물'),
  v('사슴', '7-8', 'core', '동물'),
  v('너구리', '7-8', 'core', '동물'),
  v('시계', '7-8', 'core', '생활용품', false),
  v('거울', '7-8', 'core', '생활용품'),
  v('안경', '7-8', 'core', '생활용품'),
  v('장갑', '7-8', 'core', '생활용품'),
  v('지우개', '7-8', 'core', '생활용품'),
  v('학교', '7-8', 'core', '장소', false),
  v('교실', '7-8', 'core', '장소'),
  v('마을', '7-8', 'core', '장소'),
  v('여름', '7-8', 'core', '자연'),
  v('겨울', '7-8', 'core', '자연'),
  v('마시다', '7-8', 'core', '행동'),
  v('만들다', '7-8', 'core', '행동'),
  v('예쁘다', '7-8', 'core', '상태'),
  v('졸리다', '7-8', 'core', '상태'),
  v('사촌', '7-8', 'recommended', '가족'),
  v('할아버지', '7-8', 'recommended', '가족', false),
  v('엉덩이', '7-8', 'recommended', '신체'),
  v('배꼽', '7-8', 'recommended', '신체'),
  v('눈썹', '7-8', 'recommended', '신체'),
  v('고추', '7-8', 'recommended', '음식'),
  v('양파', '7-8', 'recommended', '음식'),
  v('햄버거', '7-8', 'recommended', '음식'),
  v('김밥', '7-8', 'recommended', '음식', false),
  v('오징어', '7-8', 'recommended', '동물'),
  v('달팽이', '7-8', 'recommended', '동물'),
  v('돌고래', '7-8', 'recommended', '동물'),
  v('참새', '7-8', 'recommended', '동물'),
  v('악어', '7-8', 'recommended', '동물', false),
  v('자전거', '7-8', 'recommended', '생활용품'),
  v('바구니', '7-8', 'recommended', '생활용품'),
  v('장난감', '7-8', 'recommended', '생활용품', false),
  v('운동장', '7-8', 'recommended', '장소'),
  v('우체국', '7-8', 'recommended', '장소'),
  v('봄', '7-8', 'recommended', '자연'),
  v('가을', '7-8', 'recommended', '자연'),
  v('번개', '7-8', 'recommended', '자연'),
  v('파도', '7-8', 'recommended', '자연'),
  v('얼음', '7-8', 'recommended', '자연', false),
  v('기다리다', '7-8', 'recommended', '행동'),
  v('던지다', '7-8', 'recommended', '행동'),
  v('조용하다', '7-8', 'recommended', '상태'),
  v('뜨겁다', '7-8', 'recommended', '상태', false),
  // L1(4~6세) 1차 250개 — 그림 묶음 src/content/pictures/l1-*.ts, 2026-09-29 검수
  // 동물
  v('소', '4-6', 'core', '동물'),
  v('말', '4-6', 'core', '동물'),
  v('양', '4-6', 'core', '동물'),
  v('돼지', '4-6', 'core', '동물'),
  v('쥐', '4-6', 'core', '동물'),
  v('뱀', '4-6', 'core', '동물'),
  v('새', '4-6', 'core', '동물'),
  v('벌', '4-6', 'core', '동물'),
  v('게', '4-6', 'core', '동물'),
  v('문어', '4-6', 'core', '동물', false),
  v('상어', '4-6', 'core', '동물'),
  v('펭귄', '4-6', 'core', '동물'),
  v('부엉이', '4-6', 'recommended', '동물'),
  v('늑대', '4-6', 'recommended', '동물', false),
  v('판다', '4-6', 'core', '동물'),
  v('원숭이', '4-6', 'core', '동물'),
  v('코알라', '4-6', 'recommended', '동물'),
  v('낙타', '4-6', 'recommended', '동물'),
  v('거미', '4-6', 'core', '동물'),
  v('모기', '4-6', 'recommended', '동물'),
  v('파리', '4-6', 'recommended', '동물'),
  v('다람쥐', '4-6', 'core', '동물'),
  v('앵무새', '4-6', 'recommended', '동물'),
  v('까치', '4-6', 'recommended', '동물'),
  v('비둘기', '4-6', 'core', '동물'),
  v('독수리', '4-6', 'recommended', '동물', false),
  v('얼룩말', '4-6', 'core', '동물', false),
  v('코뿔소', '4-6', 'recommended', '동물', false),
  v('고릴라', '4-6', 'recommended', '동물'),
  v('물고기', '4-6', 'core', '동물', false),
  v('조개', '4-6', 'core', '동물'),
  v('새우', '4-6', 'recommended', '동물'),
  v('해파리', '4-6', 'recommended', '동물'),
  v('거위', '4-6', 'recommended', '동물'),
  v('염소', '4-6', 'recommended', '동물'),
  v('두더지', '4-6', 'recommended', '동물'),
  v('개', '4-6', 'core', '동물'),
  v('메뚜기', '4-6', 'recommended', '동물'),
  v('잠자리', '4-6', 'recommended', '동물'),
  v('무당벌레', '4-6', 'core', '동물'),
  v('고슴도치', '4-6', 'recommended', '동물'),
  v('캥거루', '4-6', 'recommended', '동물'),
  v('햄스터', '4-6', 'core', '동물'),
  v('수달', '4-6', 'recommended', '동물'),
  v('백조', '4-6', 'recommended', '동물', false),
  v('표범', '4-6', 'recommended', '동물'),
  v('불가사리', '4-6', 'recommended', '동물'),
  v('가재', '4-6', 'recommended', '동물'),
  // 음식
  v('사과', '4-6', 'core', '음식'),
  v('귤', '4-6', 'core', '음식'),
  v('감', '4-6', 'recommended', '음식'),
  v('떡', '4-6', 'core', '음식'),
  v('국', '4-6', 'core', '음식'),
  v('라면', '4-6', 'core', '음식'),
  v('국수', '4-6', 'core', '음식', false),
  v('쿠키', '4-6', 'core', '음식'),
  v('케이크', '4-6', 'core', '음식'),
  v('과자', '4-6', 'core', '음식'),
  v('주스', '4-6', 'core', '음식'),
  v('달걀', '4-6', 'core', '음식'),
  v('참외', '4-6', 'recommended', '음식', false),
  v('복숭아', '4-6', 'core', '음식', false),
  v('자두', '4-6', 'recommended', '음식'),
  v('레몬', '4-6', 'core', '음식'),
  v('체리', '4-6', 'core', '음식'),
  v('키위', '4-6', 'recommended', '음식'),
  v('망고', '4-6', 'recommended', '음식'),
  v('옥수수', '4-6', 'core', '음식', false),
  v('버섯', '4-6', 'core', '음식', false),
  v('콩', '4-6', 'recommended', '음식'),
  v('배추', '4-6', 'recommended', '음식'),
  v('무', '4-6', 'recommended', '음식'),
  v('가지', '4-6', 'recommended', '음식'),
  v('떡볶이', '4-6', 'core', '음식', false),
  v('소시지', '4-6', 'core', '음식'),
  v('꿀', '4-6', 'recommended', '음식'),
  v('소금', '4-6', 'recommended', '음식'),
  v('설탕', '4-6', 'recommended', '음식'),
  v('김', '4-6', 'recommended', '음식'),
  v('미역', '4-6', 'recommended', '음식'),
  v('호떡', '4-6', 'recommended', '음식'),
  v('붕어빵', '4-6', 'core', '음식'),
  v('도넛', '4-6', 'core', '음식', false),
  v('팝콘', '4-6', 'core', '음식'),
  v('젤리', '4-6', 'core', '음식'),
  v('요구르트', '4-6', 'recommended', '음식'),
  v('수프', '4-6', 'recommended', '음식'),
  v('샐러드', '4-6', 'recommended', '음식'),
  v('튀김', '4-6', 'recommended', '음식'),
  v('치킨', '4-6', 'core', '음식'),
  v('아이스크림', '4-6', 'core', '음식'),
  v('카레', '4-6', 'recommended', '음식'),
  v('떡국', '4-6', 'recommended', '음식', false),
  v('볶음밥', '4-6', 'recommended', '음식', false),
  v('멜론', '4-6', 'recommended', '음식'),
  v('파', '4-6', 'recommended', '음식'),
  // 생활용품
  v('컵', '4-6', 'core', '생활용품'),
  v('숟가락', '4-6', 'core', '생활용품', false),
  v('젓가락', '4-6', 'core', '생활용품', false),
  v('포크', '4-6', 'core', '생활용품'),
  v('접시', '4-6', 'core', '생활용품', false),
  v('그릇', '4-6', 'core', '생활용품', false),
  v('냄비', '4-6', 'core', '생활용품'),
  v('가위', '4-6', 'core', '생활용품'),
  v('테이프', '4-6', 'recommended', '생활용품'),
  v('크레파스', '4-6', 'core', '생활용품'),
  v('색연필', '4-6', 'core', '생활용품', false),
  v('칫솔', '4-6', 'core', '생활용품', false),
  v('치약', '4-6', 'core', '생활용품'),
  v('수건', '4-6', 'core', '생활용품'),
  v('빗', '4-6', 'recommended', '생활용품', false),
  v('이불', '4-6', 'core', '생활용품'),
  v('침대', '4-6', 'core', '생활용품'),
  v('의자', '4-6', 'core', '생활용품'),
  v('책상', '4-6', 'core', '생활용품', false),
  v('소파', '4-6', 'recommended', '생활용품'),
  v('전화', '4-6', 'recommended', '생활용품'),
  v('컴퓨터', '4-6', 'recommended', '생활용품'),
  v('냉장고', '4-6', 'recommended', '생활용품'),
  v('열쇠', '4-6', 'core', '생활용품', false),
  v('문', '4-6', 'core', '생활용품'),
  v('창문', '4-6', 'core', '생활용품'),
  v('상자', '4-6', 'core', '생활용품'),
  v('풍선', '4-6', 'core', '생활용품'),
  v('인형', '4-6', 'core', '생활용품'),
  v('퍼즐', '4-6', 'recommended', '생활용품'),
  v('북', '4-6', 'recommended', '생활용품'),
  v('피아노', '4-6', 'core', '생활용품'),
  v('기타', '4-6', 'recommended', '생활용품'),
  v('나팔', '4-6', 'recommended', '생활용품'),
  v('옷', '4-6', 'core', '생활용품', false),
  v('치마', '4-6', 'core', '생활용품'),
  v('단추', '4-6', 'recommended', '생활용품'),
  v('목도리', '4-6', 'recommended', '생활용품', false),
  v('잠옷', '4-6', 'recommended', '생활용품', false),
  v('운동화', '4-6', 'core', '생활용품'),
  v('장화', '4-6', 'recommended', '생활용품'),
  v('구두', '4-6', 'recommended', '생활용품'),
  v('반지', '4-6', 'recommended', '생활용품'),
  v('목걸이', '4-6', 'recommended', '생활용품', false),
  v('왕관', '4-6', 'core', '생활용품'),
  v('리본', '4-6', 'recommended', '생활용품'),
  v('그네', '4-6', 'core', '생활용품'),
  v('미끄럼틀', '4-6', 'core', '생활용품'),
  // 탈것
  v('자동차', '4-6', 'core', '탈것'),
  v('버스', '4-6', 'core', '탈것'),
  v('기차', '4-6', 'core', '탈것'),
  v('비행기', '4-6', 'core', '탈것'),
  v('트럭', '4-6', 'core', '탈것'),
  v('택시', '4-6', 'recommended', '탈것', false),
  v('오토바이', '4-6', 'recommended', '탈것'),
  v('로켓', '4-6', 'core', '탈것', false),
  v('헬리콥터', '4-6', 'recommended', '탈것'),
  v('킥보드', '4-6', 'recommended', '탈것', false),
  v('보트', '4-6', 'recommended', '탈것'),
  v('소방차', '4-6', 'core', '탈것'),
  v('경찰차', '4-6', 'core', '탈것'),
  v('구급차', '4-6', 'core', '탈것'),
  v('지하철', '4-6', 'recommended', '탈것'),
  v('우주선', '4-6', 'recommended', '탈것'),
  v('잠수함', '4-6', 'recommended', '탈것'),
  // 장소
  v('병원', '4-6', 'core', '장소'),
  v('공원', '4-6', 'core', '장소'),
  v('놀이터', '4-6', 'core', '장소', false),
  v('도서관', '4-6', 'recommended', '장소'),
  v('경찰서', '4-6', 'recommended', '장소', false),
  v('소방서', '4-6', 'recommended', '장소'),
  v('동물원', '4-6', 'core', '장소', false),
  v('수영장', '4-6', 'core', '장소'),
  v('빵집', '4-6', 'core', '장소', false),
  v('식당', '4-6', 'recommended', '장소', false),
  v('바닷가', '4-6', 'core', '장소', false),
  v('성', '4-6', 'core', '장소'),
  v('등대', '4-6', 'recommended', '장소'),
  v('텐트', '4-6', 'recommended', '장소'),
  v('탑', '4-6', 'recommended', '장소'),
  v('모래성', '4-6', 'recommended', '장소'),
  // 사람
  v('의사', '4-6', 'core', '사람'),
  v('경찰', '4-6', 'core', '사람'),
  v('소방관', '4-6', 'core', '사람'),
  v('요리사', '4-6', 'core', '사람'),
  v('선생님', '4-6', 'core', '사람'),
  v('아이', '4-6', 'core', '사람'),
  v('공주', '4-6', 'core', '사람'),
  v('왕', '4-6', 'core', '사람'),
  v('해적', '4-6', 'recommended', '사람'),
  v('우주인', '4-6', 'recommended', '사람'),
  v('농부', '4-6', 'recommended', '사람'),
  v('간호사', '4-6', 'recommended', '사람'),
  v('광대', '4-6', 'recommended', '사람'),
  v('마술사', '4-6', 'recommended', '사람', false),
  // 자연
  v('꽃', '4-6', 'core', '자연', false),
  v('잎', '4-6', 'core', '자연', false),
  v('산', '4-6', 'core', '자연'),
  v('강', '4-6', 'core', '자연'),
  v('돌', '4-6', 'core', '자연'),
  v('바위', '4-6', 'core', '자연'),
  v('섬', '4-6', 'core', '자연'),
  v('폭포', '4-6', 'recommended', '자연'),
  v('화산', '4-6', 'recommended', '자연'),
  v('숲', '4-6', 'core', '자연', false),
  v('씨앗', '4-6', 'recommended', '자연', false),
  v('선인장', '4-6', 'recommended', '자연', false),
  v('해바라기', '4-6', 'core', '자연'),
  v('장미', '4-6', 'recommended', '자연'),
  v('불', '4-6', 'core', '자연'),
  v('눈사람', '4-6', 'core', '자연', false),
  v('물방울', '4-6', 'recommended', '자연', false),
  v('모래', '4-6', 'recommended', '자연'),
  // 신체
  v('귀', '4-6', 'core', '신체'),
  v('이빨', '4-6', 'core', '신체'),
  v('혀', '4-6', 'core', '신체'),
  v('목', '4-6', 'core', '신체'),
  v('무릎', '4-6', 'recommended', '신체', false),
  v('발가락', '4-6', 'core', '신체', false),
  v('손가락', '4-6', 'core', '신체', false),
  v('손톱', '4-6', 'recommended', '신체'),
  v('머리카락', '4-6', 'recommended', '신체'),
  v('턱', '4-6', 'recommended', '신체'),
  v('볼', '4-6', 'recommended', '신체'),
  v('입술', '4-6', 'recommended', '신체', false),
  // 행동
  v('먹다', '4-6', 'core', '행동', false),
  v('웃다', '4-6', 'core', '행동', false),
  v('울다', '4-6', 'core', '행동'),
  v('걷다', '4-6', 'core', '행동', false),
  v('서다', '4-6', 'core', '행동'),
  v('씻다', '4-6', 'core', '행동', false),
  v('쓰다', '4-6', 'core', '행동'),
  v('춤추다', '4-6', 'core', '행동'),
  v('노래하다', '4-6', 'core', '행동'),
  v('타다', '4-6', 'recommended', '행동'),
  v('잡다', '4-6', 'recommended', '행동', false),
  v('열다', '4-6', 'recommended', '행동'),
  v('닫다', '4-6', 'recommended', '행동', false),
  v('밀다', '4-6', 'recommended', '행동'),
  // 상태
  v('작다', '4-6', 'core', '상태', false),
  v('길다', '4-6', 'core', '상태'),
  v('낮다', '4-6', 'recommended', '상태', false),
  v('높다', '4-6', 'core', '상태', false),
  v('차갑다', '4-6', 'core', '상태', false),
  v('무겁다', '4-6', 'recommended', '상태', false),
  v('가볍다', '4-6', 'recommended', '상태', false),
  v('슬프다', '4-6', 'core', '상태'),
  v('화나다', '4-6', 'core', '상태'),
  v('무섭다', '4-6', 'recommended', '상태', false),
  v('춥다', '4-6', 'core', '상태', false),
  v('덥다', '4-6', 'core', '상태', false),
  v('배고프다', '4-6', 'recommended', '상태'),
  v('깨끗하다', '4-6', 'recommended', '상태', false),
  v('더럽다', '4-6', 'recommended', '상태', false),
];

/**
 * 2단계 쉬운 단어 5개 (+수박): 받침·쌍자음·ㅐ 없는 두 글자이고 실제 녹음 음원 목록에 있는 단어.
 * 녹음이 있다는 이유만으로 쉬운 단어가 되지는 않는다 (꼬리·개미·바나나는 뒤 단계에서 낸다).
 */
export const EASY_FIVE = ['나무', '바다', '나비', '사자', '다리'];

/** 2단계에 더 섞는 쉬운 단어: 받침·쌍자음·ㅐ 없는 두 글자 (녹음은 아직 없다) */
export const EASY_MORE = ['모자', '아기', '머리', '피자', '오리', '비누'];

export function vocabById(id: string): VocabEntry | undefined {
  return VOCAB.find((x) => x.id === id);
}

export function packWords(pack: PackId, includeRecommended: boolean): VocabEntry[] {
  return VOCAB.filter((x) => x.pack === pack && (includeRecommended || x.tier === 'core'));
}
